### ISSUE TITLE
运行bash scripts/generate.sh --input-source interactive --sequential-initialization报错

### ISSUE THREAD

**Issue by Maxhyl** [THUDM/GLM-130B#100]
你好，我的环境是6*A6000(48G),运行上面命令报错如下：
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/home/edcuser/models/glm/GLM-130B-main/generate.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-03-14_11:22:52
  host      : localhost.localdomain
  rank      : 7 (local_rank: 7)
  exitcode  : 1 (pid: 160925)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-03-14_11:22:52
  host      : localhost.localdomain
  rank      : 6 (local_rank: 6)
  exitcode  : 1 (pid: 160924)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html

请问这个问题怎么解决？

**Comment by sukibean163** [comment]
我也出现了同样的问题，请问是如何解决的？

**Comment by Maxhyl** [comment]
> 我在4张4090gpu上，也出现了类似的问题，请问是如何解决的？

看报错信息前面提示的哪行代码报错，根据报错行提示修改就好了

**Comment by sukibean163** [comment]
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
WARNING: No training data specified
WARNING: No training data specified
WARNING: No training data specified
using world size: 4 and model-parallel size: 4 
> padded vocab (size: 150528) with 0 dummy tokens (new size: 150528)
WARNING: No training data specified
> initializing model parallel with size 4
> Set tokenizer as a icetk-glm-130B tokenizer! Now you can get_tokenizer() everywhere.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -7) local_rank: 0 (pid: 4660) of binary: /home/sukibean/bin/python
Traceback (most recent call last):
  File "/home/sukibean/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/sukibean/.local/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/sukibean/.local/lib/python3.8/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/home/sukibean/.local/lib/python3.8/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/sukibean/.local/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/sukibean/.local/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/home/sukibean/work/src/python/GLM-130B-main/generate.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-06-08_02:34:04
  host      : 3046826faa76
  rank      : 1 (local_rank: 1)
  exitcode  : -7 (pid: 4661)
  error_file: <N/A>
  traceback : Signal 7 (SIGBUS) received by PID 4661
[2]:
  time      : 2023-06-08_02:34:04
  host      : 3046826faa76
  rank      : 2 (local_rank: 2)
  exitcode  : -7 (pid: 4662)
  error_file: <N/A>
  traceback : Signal 7 (SIGBUS) received by PID 4662
[3]:
  time      : 2023-06-08_02:34:04
  host      : 3046826faa76
  rank      : 3 (local_rank: 3)
  exitcode  : -7 (pid: 4663)
  error_file: <N/A>
  traceback : Signal 7 (SIGBUS) received by PID 4663
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-06-08_02:34:04
  host      : 3046826faa76
  rank      : 0 (local_rank: 0)
  exitcode  : -7 (pid: 4660)
  error_file: <N/A>
  traceback : Signal 7 (SIGBUS) received by PID 4660
============================================================

**Comment by sukibean163** [comment]
> WARNING:torch.distributed.run:
> 
> Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
> 
> WARNING: No training data specified WARNING: No training data specified WARNING: No training data specified using world size: 4 and model-parallel size: 4
> 
> > padded vocab (size: 150528) with 0 dummy tokens (new size: 150528)
> > WARNING: No training data specified
> > initializing model parallel with size 4
> > Set tokenizer as a icetk-glm-130B tokenizer! Now you can get_tokenizer() everywhere.
> > ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -7) local_rank: 0 (pid: 4660) of binary: /home/sukibean/bin/python
> > Traceback (most recent call last):
> > File "/home/sukibean/bin/torchrun", line 8, in 
> > sys.exit(main())
> > File "/home/sukibean/.local/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/**init**.py", line 346, in wrapper
> > return f(*args, **kwargs)
> > File "/home/sukibean/.local/lib/python3.8/site-packages/torch/distributed/run.py", line 794, in main
> > run(args)
> > File "/home/sukibean/.local/lib/python3.8/site-packages/torch/distributed/run.py", line 785, in run
> > elastic_launch(
> > File "/home/sukibean/.local/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 134, in **call**
> > return launch_agent(self._config, self._entrypoint, list(args))
> > File "/home/sukibean/.local/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
> > raise ChildFailedError(
> > torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
> > ============================================================
> > /home/sukibean/work/src/python/GLM-130B-main/generate.py FAILED
> 
> ## Failures:
> [1]:
> time : 2023-06-08_02:34:04
> host : 3046826faa76
> rank : 1 (local_rank: 1)
> exitcode : -7 (pid: 4661)
> error_file: <N/A>
> traceback : Signal 7 (SIGBUS) received by PID 4661
> [2]:
> time : 2023-06-08_02:34:04
> host : 3046826faa76
> rank : 2 (local_rank: 2)
> exitcode : -7 (pid: 4662)
> error_file: <N/A>
> traceback : Signal 7 (SIGBUS) received by PID 4662
> [3]:
> time : 2023-06-08_02:34:04
> host : 3046826faa76
> rank : 3 (local_rank: 3)
> exitcode : -7 (pid: 4663)
> error_file: <N/A>
> traceback : Signal 7 (SIGBUS) received by PID 4663
> # Root Cause (first observed failure):
> [0]:
> time : 2023-06-08_02:34:04
> host : 3046826faa76
> rank : 0 (local_rank: 0)
> exitcode : -7 (pid: 4660)
> error_file: <N/A>
> traceback : Signal 7 (SIGBUS) received by PID 4660

generate.py报错，但是没有明确的信息

**Comment by Hongbin98** [comment]
> OMP_NUM_THREADS

请问最后解决了吗？遇到了一样的问题
