### ISSUE TITLE
Does GLM-130 B support [sMASK] for sentence generation?

### ISSUE THREAD

**Issue by lomizandtyd** [THUDM/GLM-130B#12]
I'm developing a chat bot on top of GLM-130B.

Currently I'm using "[MASK]" at the end of dialogue for bot's response generation.
[gMASK] is too slow for me on my 8xV100 server.

Your GLM repo https://github.com/THUDM/GLM reports [sMASK] could be used for sentence generation.
But I didn't find any doc in this repo. Does GLM-130 B support [sMASK] for sentence generation?

Do you have any plan to export more API of GLM-130 B ? Such as compute LM perplexity / Multiple choice selection or any other features? Since you have already test the model on Few-CLUE, there must be ways to utilize those features.

**Comment by Xiao9905** [comment]
@lomizandtyd Hi,

Thanks for your interest in GLM-130B! 

> Currently I'm using "[MASK]" at the end of dialogue for bot's response generation.

That's cool! Looking forward to your application online, and please contact as we can also help to promote it for you.

> Your GLM repo https://github.com/THUDM/GLM reports [sMASK] could be used for sentence generation.
> But I didn't find any doc in this repo. Does GLM-130 B support [sMASK] for sentence generation?

Unfortunately, we didn't implement [sMASK] in GLM-130B since it harms the efficiency of pre-training. However, we are planning to train GLM-130B for a few steps on [sMASK] objectives to enable this feature. Please wait for a few days as we are working on it : )

> Do you have any plan to export more API of GLM-130 B ? Such as compute LM perplexity / Multiple choice selection or any other features? Since you have already test the model on Few-CLUE, there must be ways to utilize those features.

That sounds great. But it may not be our first priority since we are now having a hard time sparing any machines for such a goal. Thanks for your suggestions.

**Comment by lomizandtyd** [comment]
Could you provide some guidelines about how to compute PPL/logprobs on GLM-130 B?

**Comment by Sengxian** [comment]
Hello @lomizandtyd, we have recently implemented preliminary code to test PPL on tasks such as WikiText103 and PTB, you can check out the [eval-lm branch](https://github.com/THUDM/GLM-130B/blob/eval-lm/tasks/language-modeling/wikitext-103.yaml) and the code will be merged into the main branch after further testing. If you have any questions, please feel free to ask!

**Comment by lomizandtyd** [comment]
Thanks, that's what I want.
