### ISSUE TITLE
about：conda install -y cmake numpy pybind11 pytorch torchvision cudatoolkit-dev cudnn

### ISSUE THREAD

**Issue by KAYY123** [THUDM/GLM-130B#14]
Excuse me, I will report an error when I execute this statement. How to solve it？

**Comment by KAYY123** [comment]
![图片](https://user-images.githubusercontent.com/59907326/186066007-1c0d0c6a-ad8f-4f3e-9b3b-5b072a88b3b0.png)

**Comment by Sengxian** [comment]
Hello, @KAYY123. Please try `conda install -c conda-forge cudatoolkit-dev` to see if it still show an error.

**Comment by KAYY123** [comment]
Thanks!
Run `conda install -c conda-forge cudatoolkit-dev` and there is no error. Does this command `conda install -y cmake numpy pybind11 pytorch torchvision cudatoolkit-dev cudnn` install these packages together? In addition to running this command `conda install -c conda-forge cudatoolkit-dev,` what command do I need to run to have the same effect as this command `conda install -y cmake numpy pybind11 pytorch torchvision cudatoolkit-dev cudnn`?

**Comment by Sengxian** [comment]
It seems that the problem is that our .condarc file has conda-forge added to the search channel by default. You can install `cudatoolkit-dev` and other packages with two commands separately, or you can specify multiple channels with one command, `conda install -c conda-forge -y cmake numpy pybind11 pytorch torchvision cudatoolkit-dev cudnn`.
