### ISSUE TITLE
Use GLM-130B on machine translation task.

### ISSUE THREAD

**Issue by BrightXiaoHan** [THUDM/GLM-130B#46]
Hi!
After reading a lot of information, it seems that in the field of machine translation, it is more likely to use a small amount of parallel corpus for fine-tuning, and I feel that it may work better for some low-resource languages. But it seems that it is difficult to improve the performance of rich corpus languages. 

I have checked GLM papers and found no performance analysis on the machine translation task. Is it possible to use GLM-130B to improve machine translation performance in English-Chinese translation tasks? Are there any experiments or best practices about this?

**Comment by Xiao9905** [comment]
@BrightXiaoHan Hi,

Using pre-trained LLMs for machine translation would be interesting. However, I am sorry that we do not have enough time to dive into the topic. I think it is absolutely possible as we also observe some evidence in zero-shot/few-shot translation of GLM-130B.

If you would conduct experiments with GLM/GLM-130B on English-Chinese translation, we are more than glad to include your results and cite you in our updated paper. Thanks again for your interest in GLM-130B.

**Comment by BrightXiaoHan** [comment]
Why didn't we consider adding a TLM objective, similar to [XLM](https://arxiv.org/abs/1901.07291), in the training process, which should feel more beneficial for cross-language tasks between Chinese and English?

**Comment by Xiao9905** [comment]
Thanks for your suggestion. However, translation is not a main purpose of GLM-130B's training. Our goal is to build a language model that understand people's query well. Therefore, we'd like to invest more expensive computation on training it on general corpora rather than translation. On the other hand, the zero-shot/few-shot translation ability could arise automatically, which is enough for common use.

If you wanna improve GLM-130B's translation between English and Chinese, we encourage you to fine-tune it on translation datasets via the [code repo for training](https://github.com/THUDM/LargeScale). We have been too busy recently and are afraid that we can't spend more time on fine-tuning GLM-130B on translation datasets.

**Comment by XiaoqingNLP** [comment]
@BrightXiaoHan Hi, do you have to try it on downstream tasks?
