### ISSUE TITLE
1xA100 80GB inference in INT4?

### ISSUE THREAD

**Issue by charlesfrye** [THUDM/GLM-130B#60]
Thanks for making such a powerful model widely available! Very impressive work to get it to run on a single node using all open source methods.

I took it for a spin on an 8x A100 40GB machine and got some nice results.

Have you tried running the model on a single A100 80GB or an H100? Can it run without off-loading the weights to CPU?

I looked at the low resource info and did some simple calculations and it looks like
1. The FP16 model has 260GB of weights and runs smoothly on 320GB of VRAM (eg an 8x A100 40GB or 4x A100 80GB).
2. The INT4 model has 65GB of weights, so it should run smoothly on 65 * 320/260 = 80 GB VRAM.

If that's the case, it'd be great to know because single-card setups are even easier to work with than single-node, and the H100s are coming soon.

**Comment by Sengxian** [comment]
Hello @charlesfrye, the actual VRAM usage for INT4 inference is around ~88G due to runtime memory consumption. Unfortunately, it's impossible to run INT4 model in a single 80G card for now. However, more advanced quantization techniques such as GPT-Q allows INT3 quantization, which can further reduce memory usage. We've got some preliminary results for this, but we haven't gotten around to putting together a release yet.

**Comment by charlesfrye** [comment]
Ah bummer! Thanks for the quick reply, and thanks again for making this model!
